# Generated by Django 5.2.10 on 2026-01-19 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('limite_usuarios', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('FISCAL', 'Fiscal/Notas'), ('DP', 'Departamento Pessoal'), ('CONTABIL', 'Contabilidade')], max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.empresa')),
            ],
        ),
    ]
