# Generated by Django 5.2.10 on 2026-01-20 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='PedidoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao_solicitacao', models.TextField()),
                ('arquivo_enviado', models.FileField(blank=True, null=True, upload_to='pedidos/%Y/%m/')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('concluido', models.BooleanField(default=False)),
                ('empresa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='documentos.empresa')),
                ('setor_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.setor')),
            ],
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
