# Generated by Django 5.2.10 on 2026-01-22 19:46

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_setor_pedidodocumento_delete_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodocumento',
            name='usuario_solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_feitos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidodocumento',
            name='arquivo_enviado',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.caminho_resposta_cliente),
        ),
    ]
