# Generated by Django 5.2.10 on 2026-01-28 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_agendamentopedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentopedido',
            name='empresa_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_empresa', to='documentos.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidodocumento',
            name='usuario_destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_recebidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamentopedido',
            name='usuario_destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_programados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamentopedido',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_feitos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidodocumento',
            name='empresa_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_empresa', to='documentos.empresa'),
        ),
        migrations.AlterField(
            model_name='pedidodocumento',
            name='setor_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.setor'),
        ),
        migrations.AlterField(
            model_name='pedidodocumento',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
