# Generated by Django 5.2.10 on 2026-01-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_agendamentopedido_empresa_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodocumento',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidodocumento',
            name='justificativa_exclusao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
