# Generated by Django 5.2.10 on 2026-02-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_pedidodocumento_excluido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contabilidade', models.CharField(default='Minha Contabilidade', max_length=200)),
                ('logo_contabilidade', models.ImageField(blank=True, null=True, upload_to='logos_sistema/')),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
