# Generated by Django 5.2.10 on 2026-02-02 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_configuracaosistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodocumento',
            name='usuario_exclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_excluidos_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
