# Generated by Django 5.2.10 on 2026-01-20 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_setor_pedidodocumento_delete_documento'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_setor', to='documentos.setor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('CONTABILIDADE', 'Funcionário Contabilidade'), ('CLIENTE', 'Cliente/Empresa')], default='CLIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_empresa', to='documentos.empresa'),
        ),
    ]
