# Generated by Django 5.2.10 on 2026-01-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_setor_usuario_tipo_alter_usuario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('CONTABILIDADE', 'Funcionário Contabilidade'), ('ADMIN_CONTABILIDADE', 'Administrador Contabilidade'), ('CLIENTE', 'Cliente/Empresa')], default='CLIENTE', max_length=20),
        ),
    ]
